# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressources\add_ssbv_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_ssbv_form(object):
    def setupUi(self, add_ssbv_form):
        add_ssbv_form.setObjectName("add_ssbv_form")
        add_ssbv_form.resize(710, 381)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(add_ssbv_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(add_ssbv_form)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.splitter = QtWidgets.QSplitter(add_ssbv_form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_ssbv_field = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_ssbv_field.setObjectName("le_ssbv_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_ssbv_field)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb_ssbv_layer = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_ssbv_layer.setObjectName("cb_ssbv_layer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_ssbv_layer)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setItalic(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pb_cancel = QtWidgets.QPushButton(add_ssbv_form)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pb_ok = QtWidgets.QPushButton(add_ssbv_form)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(add_ssbv_form)
        QtCore.QMetaObject.connectSlotsByName(add_ssbv_form)

    def retranslateUi(self, add_ssbv_form):
        _translate = QtCore.QCoreApplication.translate
        add_ssbv_form.setWindowTitle(_translate("add_ssbv_form", "Ajouter les sous bassins versants aux entitées du projet"))
        self.label_3.setText(_translate("add_ssbv_form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Ajouter les Sous Bassins Versants aux entitées du projet</span></p></body></html>"))
        self.label_2.setText(_translate("add_ssbv_form", "<html>\n"
"<head/>\n"
"<body>\n"
"<p style=\"margin-bottom: 2px;\">Nom du champ \" sous bassin versant id\"</p>\n"
"<p style=\"margin-top: 0;\">\n"
"<span style=\"font-size:7pt; font-style:italic;\">(dans les autres couches)</span>\n"
"</p>\n"
"</body>\n"
"</html>"))
        self.le_ssbv_field.setText(_translate("add_ssbv_form", "ssbv_id"))
        self.label.setText(_translate("add_ssbv_form", "Couche des sous bassins versants"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("add_ssbv_form", "Choisir les couches à traiter"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("add_ssbv_form", "Couche"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("add_ssbv_form", "(Seulement les entitées sélectionnées)"))
        self.pb_cancel.setText(_translate("add_ssbv_form", "Cancel"))
        self.pb_ok.setText(_translate("add_ssbv_form", "Ok"))
