# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressources\create_sd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_sd_form(object):
    def setupUi(self, create_sd_form):
        create_sd_form.setObjectName("create_sd_form")
        create_sd_form.resize(751, 348)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(create_sd_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(create_sd_form)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.splitter = QtWidgets.QSplitter(create_sd_form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_project_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_project_name.setObjectName("le_project_name")
        self.horizontalLayout_2.addWidget(self.le_project_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_project_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_project_path.setObjectName("le_project_path")
        self.horizontalLayout.addWidget(self.le_project_path)
        self.pb_project_path = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_project_path.setStyleSheet("image: url(:/img/img/folder.svg);")
        self.pb_project_path.setText("")
        self.pb_project_path.setObjectName("pb_project_path")
        self.horizontalLayout.addWidget(self.pb_project_path)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.mGroupBox = QgsCollapsibleGroupBox(self.layoutWidget)
        self.mGroupBox.setCollapsed(True)
        self.mGroupBox.setObjectName("mGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.mGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.le_db_name = QtWidgets.QLineEdit(self.mGroupBox)
        self.le_db_name.setObjectName("le_db_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_db_name)
        self.label_4 = QtWidgets.QLabel(self.mGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addWidget(self.mGroupBox)
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pb_cancel = QtWidgets.QPushButton(create_sd_form)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_3.addWidget(self.pb_cancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pb_ok = QtWidgets.QPushButton(create_sd_form)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_3.addWidget(self.pb_ok)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(create_sd_form)
        QtCore.QMetaObject.connectSlotsByName(create_sd_form)

    def retranslateUi(self, create_sd_form):
        _translate = QtCore.QCoreApplication.translate
        create_sd_form.setWindowTitle(_translate("create_sd_form", "Outils d\'aide à la création d\'un Schéma Directeur"))
        self.label_3.setText(_translate("create_sd_form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Création d\'un schémas directeur</span></p></body></html>"))
        self.label_2.setText(_translate("create_sd_form", "Nom du Projet"))
        self.label.setText(_translate("create_sd_form", "Chemin de sauvegarde"))
        self.mGroupBox.setTitle(_translate("create_sd_form", "Paramètres avancés"))
        self.label_4.setText(_translate("create_sd_form", "Nom de la base de données contenant les couches de définition"))
        self.pb_cancel.setText(_translate("create_sd_form", "Cancel"))
        self.pb_ok.setText(_translate("create_sd_form", "OK"))
from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from gep_sd.form.ui import ressources_rc
