# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressources\get_and_verif_canalisation_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_get_and_verif_canalisation_form(object):
    def setupUi(self, get_and_verif_canalisation_form):
        get_and_verif_canalisation_form.setObjectName("get_and_verif_canalisation_form")
        get_and_verif_canalisation_form.resize(470, 261)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(get_and_verif_canalisation_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(get_and_verif_canalisation_form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_line_layer = QtWidgets.QComboBox(get_and_verif_canalisation_form)
        self.cb_line_layer.setObjectName("cb_line_layer")
        self.horizontalLayout.addWidget(self.cb_line_layer)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(get_and_verif_canalisation_form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(get_and_verif_canalisation_form)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pb_cancel = QtWidgets.QPushButton(get_and_verif_canalisation_form)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pb_ok = QtWidgets.QPushButton(get_and_verif_canalisation_form)
        self.pb_ok.setObjectName("pb_ok")
        self.horizontalLayout_2.addWidget(self.pb_ok)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(get_and_verif_canalisation_form)
        QtCore.QMetaObject.connectSlotsByName(get_and_verif_canalisation_form)

    def retranslateUi(self, get_and_verif_canalisation_form):
        _translate = QtCore.QCoreApplication.translate
        get_and_verif_canalisation_form.setWindowTitle(_translate("get_and_verif_canalisation_form", "Trouver et vérifier les Noeud Amont et Aval des Canalisations"))
        self.label.setText(_translate("get_and_verif_canalisation_form", "Sélectionner la couche de Canalisation"))
        self.label_2.setText(_translate("get_and_verif_canalisation_form", "Séléctionner les couches de points"))
        self.pb_cancel.setText(_translate("get_and_verif_canalisation_form", "Cancel"))
        self.pb_ok.setText(_translate("get_and_verif_canalisation_form", "Ok"))
