# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ressources\main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_form(object):
    def setupUi(self, main_form):
        main_form.setObjectName("main_form")
        main_form.resize(878, 686)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(main_form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.retranslateUi(main_form)
        QtCore.QMetaObject.connectSlotsByName(main_form)

    def retranslateUi(self, main_form):
        _translate = QtCore.QCoreApplication.translate
        main_form.setWindowTitle(_translate("main_form", "-"))
from geopal.form.ui import ressources_rc
